### ISSUE TITLE
Feature: Add shared library to project. 

### ISSUE THREAD

**Issue by cshiva** [appsquickly/XcodeEditor#21]

**Comment by GangWang** [comment]
![2015-05-07_17-21-58](https://cloud.githubusercontent.com/assets/1000877/7512212/f7d769cc-f4dd-11e4-88f9-3ce95190ec97.png)
(note:right area in image)

use this fun:
- (void)addFramework:(XCFrameworkDefinition*)frameworkDefinition

build will failed

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Crasheye", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jasperblues** [comment]
I believe for libraries this process can be used: https://github.com/appsquickly/XcodeEditor#configuring-targets

. . . however, haven't tried this in a while.

**Comment by GangWang** [comment]
3q~    I go to try it now  ;)

**Comment by jasperblues** [comment]
OK, let me know the result

**Comment by GangWang** [comment]
thank u very much ,  i use this way, and it works    ；）；）；）；）；）

----------------
 XCSourceFileDefinition* libFile = [[XCSourceFileDefinition alloc] initWithName:@"libCrasheye.a" data:[NSData dataWithContentsOfFile:aFile] type:Archive];
        [crasheyeGroup addSourceFile:libFile];
        
        XCSourceFile * libSourceFile = [project fileWithName:@"libCrasheye.a"];
        
        XCTarget* target = [project targetWithName:self.mProject.projectName];
       
        [target addMember:libSourceFile];
        
        for (NSString* configName in [target configurations])
        {
            XCProjectBuildConfig* configuration = [target configurationWithName:configName];
            NSMutableArray* headerPaths = [[NSMutableArray alloc] init];
            [headerPaths addObject:@"$(inherited)"];
            [headerPaths addObject:@"$(PROJECT_DIR)/Crasheye"];
            [configuration addOrReplaceSetting:headerPaths forKey:@"LIBRARY_SEARCH_PATHS"];
        }

----------------

**Comment by jasperblues** [comment]
welcome :) :+1:

**Comment by jasperblues** [comment]
ps: I'll add this to the README . .
