### ISSUE TITLE
Linker Error because of duplicate symbols

### ISSUE THREAD

**Issue by iljaiwas** [appsquickly/XcodeEditor#58]
When trying to compile this, I'm getting a linker error because of the way the XCProjectNotFoundException global is defined in the header file.

I tried to fix this in [my branch](https://github.com/iljaiwas/XcodeEditor) by moving that global to XCProject.m, but I might be overlooking something.

Or should I just create an PR?

**Comment by jasperblues** [comment]
I haven't noticed this before - perhaps its related to Xcode 7? If you'd like to send a PR, I'll review tomorrow.

**Comment by iljaiwas** [comment]
It might be Xcode 7, or the fact that I'm integrating your code via [CocoaSeeds](https://github.com/devxoul/CocoaSeeds), thus perhaps missing a special compiler flag defined in your .xcodeproj file.

Will send PR shortly.

**Comment by cezheng** [comment]
fixed in https://github.com/appsquickly/XcodeEditor/pull/60
