### ISSUE TITLE
feature - determine project / name directory path / project file from key window 

### ISSUE THREAD

**Issue by johndpope** [appsquickly/XcodeEditor#83]
I'm building a menu plugin and found this repo - 
while it may be clear what the project name is in 99% of use cases - consider that there are times when we want to know / dig up these values. 

Consider cherry picking a couple of classes from this code - CrasheyePluginXcode
https://github.com/GangWang/Crasheye/tree/d6c1b3abedafac040d62d85265e971bd5563cc40/CrasheyePluginXcode/class

Eg. for the first sample - 
you should be able to call 

```
   MTProject *mainProject = [MTProject projectForKeyWindow];

NSLog(@"mainProject:%@",mainProject.directoryPath);
NSLog(@"projectName:%@",mainProject.projectName);
NSLog(@"infoDictionary:%@",mainProject.infoDictionary);
NSLog(@"workspacePath:%@",mainProject.workspacePath);
NSLog(@"projectFile:%@",mainProject.projectFile);
NSLog(@"projectFileDir:%@",mainProject.projectFileDir);

XCProject* project = [[XCProject alloc] initWithFilePath:mainProject.projectName];
```

```

@interface MTProject : NSObject

@property (nonatomic, copy, readonly) NSString* directoryPath;
@property (nonatomic, copy, readonly) NSString* projectName;
@property (nonatomic, copy, readonly) NSDictionary* infoDictionary;
@property (nonatomic, readonly) NSString* workspacePath;

@property (nonatomic, copy, readonly) NSString* projectFile;
@property (nonatomic, copy, readonly) NSString* projectFileDir;

+ (instancetype)projectForKeyWindow;

- (id)initWithName:(NSString*)name path:(NSString*)path;


- (BOOL)containsFileWithName:(NSString*)fileName;

@end



```

**Comment by jasperblues** [comment]
Sounds good. Until now coupling has only been via .xcodeproj file, no dependency outside of standard Cocoa. However, this sounds useful enough to go beyond that. Do you want to send a PR?

**Comment by johndpope** [comment]
fyi - https://github.com/markohlebar/Peckham/blob/a9c51f05999c8af5d1e8ffed87a9946b1f364bbd/MHImportBuster/External/Benoit/MHXcodeDocumentNavigator.m

**Comment by johndpope** [comment]
spring cleaning github issues.
@jasperblues - thanks for your efforts here.
