### ISSUE TITLE
Doesn't get all the XCBuildConfiguration's in the file

### ISSUE THREAD

**Issue by jflow** [appsquickly/XcodeEditor#84]
I need to manipulate the code signing parameters of the xcodeproj file. In the one release configuration that I get the one "CODE_SIGN_IDENTITY[sdk=iphoneos*]" but I need to edit the following parameters:

- CODE_SIGN_IDENTITY
- PROVISIONING_PROFILE
- DEVELOPMENT_TEAM

I can't seem to find a way to get to these key/values in side the XCProjectBuildConfig class. Any ideas on how to accomplish this?

**Comment by jasperblues** [comment]
https://github.com/appsquickly/XcodeEditor#configuring-targets

Does this work for you?

**Comment by jflow** [comment]
It works perfectly for our needs. Thank you very much for the quick response and for providing the project.
