### ISSUE TITLE
Support for Copy Bundle Phases

### ISSUE THREAD

**Issue by Cyqlblgy** [appsquickly/XcodeEditor#88]
Good repo, I was trying to remove/add some plist files to existing targets, I tried removeResourceWithKey and removeMemberWithKey but didn't seem work, any idea how to achieve that?

**Comment by jasperblues** [comment]
You mean you can't remove an item from a target? There's some bug-fixes on the no-generics branch that corrected a similar issue.

**Comment by Cyqlblgy** [comment]
Yes @jasperblues , I will give it a try on that branch thanks.

**Comment by Cyqlblgy** [comment]
Thank you @jasperblues it did work, do you know if I can add some XML and Plist file to a group

**Comment by jasperblues** [comment]
From memory, I think you have to add the recursive members to the target, rather than the group itself.

**Comment by jasperblues** [comment]
Oh, and you'll also need to set the SourceFileType - I checked and XML does not seem to be in there. So what you do is add one manually, save, open the plist file and look for it. Then create a new SourceFileType that matches.

**Comment by Cyqlblgy** [comment]
@jasperblues Thanks for your help, it worked perfectly.
